language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pylint
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
script: coverage run -m py.test discopy/*.py test/*.py --doctest-modules # run tests
after_success:
  - coverage report -m
  - coverage xml
  - codecov # submit coverage
  - pylint discopy
